name: mlr
channels:
  - defaults
    #- conda-forge
dependencies:
  - python=3.8
  - pip=21.1.3
  - numpy=1.19.2
  - absl-py=0.13.0
  - pyparsing=2.4.7
  - jupyterlab=3.0.14
  - scikit-image=0.18.1
  - nvidia::cudatoolkit=11.1
  - pytorch::pytorch==1.10.0
  - pytorch::torchvision=0.11.0
  - pytorch::torchaudio
  - pip:
    - mujoco-py<2.2,>=2.1
    - chardet
    - gym==0.22
    - termcolor==1.1.0
    # - git+https://github.com/deepmind/dm_control.git unreleased
    - dm_control # use this instead of the above
    - git+https://github.com/denisyarats/dmc2gym.git@06f7e33
    - tb-nightly
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.4
    - hydra-core==1.1.0
    - hydra-submitit-launcher==1.1.5
    - pandas==1.3.0
    - ipdb==0.13.9
    - yapf==0.31.0
      # - mujoco_py==2.0.2.13
    - sklearn==0.0
    - matplotlib==3.4.2
    - opencv-python==4.5.3.56
    - wandb
    - absl-py
    - timm==1.0.9 # py3.8+
    - torchelastic==0.2.2 #py3.8+
    - kornia==0.4.1
